//
// Generated file, do not edit! Created by nedtool 5.2 from InterestMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INTERESTMSG_M_H
#define __INTERESTMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>InterestMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet InterestMsg
 * {
 *     int interest;
 *     int saddress;
 * }
 * </pre>
 */
class InterestMsg : public ::omnetpp::cPacket
{
  protected:
    int interest;
    int saddress;

  private:
    void copy(const InterestMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InterestMsg&);

  public:
    InterestMsg(const char *name=nullptr, short kind=0);
    InterestMsg(const InterestMsg& other);
    virtual ~InterestMsg();
    InterestMsg& operator=(const InterestMsg& other);
    virtual InterestMsg *dup() const override {return new InterestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getInterest() const;
    virtual void setInterest(int interest);
    virtual int getSaddress() const;
    virtual void setSaddress(int saddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const InterestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, InterestMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INTERESTMSG_M_H

