//
// Generated file, do not edit! Created by nedtool 5.2 from SubscriberMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SUBSCRIBERMSG_M_H
#define __SUBSCRIBERMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>SubscriberMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet SubscriberMsg
 * {
 *     int feedForSub;
 * }
 * </pre>
 */
class SubscriberMsg : public ::omnetpp::cPacket
{
  protected:
    int feedForSub;

  private:
    void copy(const SubscriberMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SubscriberMsg&);

  public:
    SubscriberMsg(const char *name=nullptr, short kind=0);
    SubscriberMsg(const SubscriberMsg& other);
    virtual ~SubscriberMsg();
    SubscriberMsg& operator=(const SubscriberMsg& other);
    virtual SubscriberMsg *dup() const override {return new SubscriberMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFeedForSub() const;
    virtual void setFeedForSub(int feedForSub);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SubscriberMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SubscriberMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SUBSCRIBERMSG_M_H

